version: "3.8"

services:
  elixir:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1.13-otp-25"
        PHOENIX_VERSION: "1.6.11"
        NODE_VERSION: "16"

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
